name: ci

on: push

jobs:
    dialyzer:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.2.1

            - id: beam

              uses: erlef/setup-beam@v1.18.2

              with:
                  elixir-version: ${{ matrix.elixir }}

                  otp-version: ${{ matrix.otp }}

            - uses: actions/cache@v4.2.2

              with:
                  key: ${{ github.job }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ hashFiles('mix.lock') }}-1

                  path: _build

            - run: mix deps.get

            - run: mix dialyzer

        strategy:
            matrix:
                elixir:
                    - 1.17.x
                    - 1.16.x
                    - 1.15.x

                otp:
                    - 27.x
                    - 26.x
                    - 25.x
                    - 24.x

                exclude:
                    - elixir: 1.15.x

                      otp: 27.x

                    - elixir: 1.16.x

                      otp: 27.x

                    - elixir: 1.17.x

                      otp: 24.x

    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.2.1

            - id: beam

              uses: erlef/setup-beam@v1.18.2

              with:
                  elixir-version: ${{ matrix.elixir }}

                  otp-version: ${{ matrix.otp }}

            - uses: actions/cache@v4.2.2

              with:
                  key: ${{ github.job }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ hashFiles('mix.lock') }}-1

                  path: _build

            - run: mix deps.get

            - run: mix test

        strategy:
            matrix:
                elixir:
                    - 1.17.x
                    - 1.16.x
                    - 1.15.x

                otp:
                    - 27.x
                    - 26.x
                    - 25.x
                    - 24.x

                exclude:
                    - elixir: 1.15.x

                      otp: 27.x

                    - elixir: 1.16.x

                      otp: 27.x

                    - elixir: 1.17.x

                      otp: 24.x
